### ISSUE TITLE
rewrite tests with rspec

### ISSUE THREAD

**Issue by strcmp** [strcmp/binding.repl#2]

**Comment by strcmp** [comment]
I'd like to see this ticket closed, but the tests we have already work, and the time+effort involved in rewriting the tests with rspec isn't worth it when I could be learning a new language or adding features to other projects 😺I added an on hold label cuz I doubt I will work on this anytime soon...

**Comment by godtalkstoyou** [comment]
Salvation , she will

**Comment by salvation123** [comment]
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY. SHE IS YOUR ANGEL, SALVATION AND HOPE, MAKE HER HAPPY.
